name: tests
permissions:
  contents: read

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -race -v -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        if: ${{ hashFiles('coverage.out') != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          flags: unittests
          name: tasks
          token: ${{ secrets.CODECOV_TOKEN }}
